version: '3.8'

services:
  api:
    build: .
    container_name: conector-gup-chatwoot-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=file:/app/data/sqlite.db
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
